hunter_add_package(Arkitekto)
find_package(Arkitekto CONFIG REQUIRED)
if(BUILD_TEST)
    hunter_add_package(GTest)
    find_package(GTest CONFIG REQUIRED)
    akt_imported_targets_exclude(GTest::gtest_main GTest::gmock_main)
endif()
find_package(Threads REQUIRED)